const booksActionType = {
  BOOKS_FETCH: 'BOOKS_FETCH',
  BOOKS_FETCH_REQUESTED: 'BOOKS_FETCH_REQUESTED',
  BOOKS_FETCH_SUCCEEDED: 'BOOKS_FETCH_SUCCEEDED',
  BOOKS_FETCH_ERROR: 'BOOKS_FETCH_ERROR',

  BOOKS_REMOVE_REQUESTED: 'BOOKS_REMOVE_REQUESTED',
  BOOKS_REMOVE_SUCCEEDED: 'BOOKS_REMOVE_SUCCEEDED',
  BOOKS_REMOVE_ERROR: 'BOOKS_REMOVE_ERROR'
};

export { booksActionType };
