const booksActionType = {
  BOOKS_FETCH: 'BOOKS_FETCH',
  BOOKS_FETCH_REQUESTED: 'BOOKS_FETCH_REQUESTED',
  BOOKS_FETCH_SUCCEEDED: 'BOOKS_FETCH_SUCCEEDED',
  BOOKS_FETCH_ERROR: 'BOOKS_FETCH_ERROR'
};

export { booksActionType };
